# Generated by Django 3.2.23 on 2023-11-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('handle', models.CharField(max_length=50, verbose_name='Handle')),
                ('cookies', models.CharField(max_length=300, verbose_name='Cookies')),
            ],
            options={
                'verbose_name': 'TwitterAccount',
                'verbose_name_plural': 'TwitterAccounts',
            },
        ),
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets_count', models.IntegerField(verbose_name='Tweets Count')),
                ('replys_count', models.IntegerField(verbose_name='Replys Count')),
                ('messages_count', models.IntegerField(verbose_name='Messages Count')),
                ('followers_count', models.IntegerField(verbose_name='Followers Count')),
                ('following_count', models.IntegerField(verbose_name='Following Count')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
