# Generated by Django 3.2.23 on 2023-11-29 13:33

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 29, 13, 33, 18, 705758, tzinfo=utc), verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
