# Generated by Django 3.2.23 on 2023-12-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_project_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgURL',
            field=models.ImageField(null=True, upload_to='projects-images/'),
        ),
    ]
