# Generated by Django 3.2.23 on 2023-12-25 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20231224_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogininfo',
            name='name',
            field=models.CharField(default='null', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountlogininfo',
            name='screen_name',
            field=models.CharField(default='@null', max_length=50, verbose_name='Handle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Updated Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Updated Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id_str', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('favorite_count', models.IntegerField(verbose_name='Likes Count')),
                ('reply_count', models.IntegerField(verbose_name='Replies Count')),
                ('retweet_count', models.IntegerField(verbose_name='Retweet Count')),
                ('user_id_str', models.CharField(max_length=50, verbose_name='ID')),
                ('bookmark_count', models.IntegerField(verbose_name='BookMarked Count')),
                ('full_text', models.TextField(verbose_name='Body')),
                ('created_at', models.CharField(max_length=60, verbose_name='Created At')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('sort_timestamp', models.DateTimeField(verbose_name='Chat Date & Time')),
                ('status', models.CharField(max_length=50, unique=True, verbose_name='Status')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chat',
            },
        ),
    ]
