# Generated by Django 3.2.23 on 2023-12-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_accountlogininfo_profileimgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
