# Generated by Django 3.2.23 on 2024-01-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_alter_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogininfo',
            name='screen_name',
            field=models.CharField(max_length=50, verbose_name='Screen Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imgURL',
            field=models.ImageField(null=True, upload_to='./twitter/projects-images/'),
        ),
        migrations.CreateModel(
            name='FollowUnFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField(verbose_name='Followers Count')),
                ('following', models.IntegerField(verbose_name='Following Count')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount')),
            ],
            options={
                'verbose_name': 'Follower & Following Count',
                'verbose_name_plural': 'Follower & Following Counts',
            },
        ),
    ]
