# Generated by Django 3.2.23 on 2024-01-02 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_auto_20240102_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
