# Generated by Django 3.2.23 on 2024-01-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_auto_20240102_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id_str', models.CharField(max_length=50, unique=True, verbose_name='ID')),
                ('favorite_count', models.IntegerField(verbose_name='Likes Count')),
                ('reply_count', models.IntegerField(verbose_name='Replies Count')),
                ('retweet_count', models.IntegerField(verbose_name='Retweet Count')),
                ('user_id_str', models.CharField(max_length=50, verbose_name='ID')),
                ('bookmark_count', models.IntegerField(verbose_name='BookMarked Count')),
                ('full_text', models.TextField(verbose_name='Body')),
                ('in_reply_to_screen_name', models.CharField(max_length=50, verbose_name='Replying to')),
                ('created_at', models.CharField(max_length=60, verbose_name='Created At')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
    ]
