# Generated by Django 3.2.23 on 2024-01-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_auto_20240104_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogininfo',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.twitteraccount'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.project'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.twitteraccount'),
        ),
        migrations.AlterField(
            model_name='followunfollow',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.twitteraccount'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.twitteraccount'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.twitteraccount'),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.agent'),
        ),
    ]
