# Generated by Django 3.2.23 on 2024-01-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0016_auto_20240108_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sort_timestamp',
            new_name='chat_datetime',
        ),
        migrations.AlterField(
            model_name='accountlogininfo',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteraccount'),
        ),
    ]
