# Generated by Django 3.2.23 on 2024-01-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0018_alter_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogininfo',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
    ]
