# Generated by Django 3.2.23 on 2024-01-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0019_auto_20240114_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='quoted_retweted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotedretwetedfrom', to='twitter.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retwetedfrom', to='twitter.tweet'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='conversation_id',
            field=models.CharField(max_length=50, verbose_name='Conversation ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='conversation_id_str',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user_id_str',
            field=models.CharField(max_length=50, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='conversation_id_str',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_id_str',
            field=models.CharField(max_length=50, verbose_name='User ID'),
        ),
    ]
