# Generated by Django 3.2.23 on 2024-01-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0020_auto_20240116_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repliedfrom', to='twitter.reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='in_reply_to_screen_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Replying to'),
        ),
    ]
