# Generated by Django 3.2.23 on 2024-01-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0021_auto_20240116_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialink',
            name='url',
            field=models.URLField(unique=True, verbose_name='Media URL'),
        ),
    ]
