# Generated by Django 3.2.23 on 2024-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0022_alter_medialink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='followunfollow',
            name='likes',
            field=models.IntegerField(default=None, verbose_name='Likes Count'),
            preserve_default=False,
        ),
    ]
