# Generated by Django 3.2.23 on 2024-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0023_followunfollow_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followunfollow',
            name='likes',
            field=models.IntegerField(null=True, verbose_name='Likes Count'),
        ),
    ]
