# Generated by Django 3.2.23 on 2024-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0024_alter_followunfollow_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='conversation_id_str',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='conversation_id_str',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID'),
        ),
    ]
