# Generated by Django 3.2.23 on 2024-01-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0026_telegrambotuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlogininfo',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.twitteraccount'),
        ),
        migrations.AlterField(
            model_name='telegrambotuser',
            name='telegram_user_id',
            field=models.IntegerField(verbose_name='Telegram User ID'),
        ),
    ]
